// define the "base layer" that presets rest upon. 
// preset parameters will override any parameters from defaults.
// the idea is to keep the preset definitions concise by leaving out parameters which are 
// 1) generally the same across most presets
// 2) not relevant or characteristic of that preset

// Sourced from Draw Things: Select "Restore Defaults", then "Copy Configuration"
{
    "aestheticScore": 6,
    "batchCount": 1,
    "batchSize": 1,
    "clipSkip": 1,
    "clipWeight": 1,
    "controls": [],
    "cropLeft": 0,
    "cropTop": 0,
    "decodingTileHeight": 640,
    "decodingTileOverlap": 128,
    "decodingTileWidth": 640,
    "diffusionTileHeight": 1024,
    "diffusionTileOverlap": 128,
    "diffusionTileWidth": 1024,
    "fps": 5,
    "guidanceScale": 7.5,
    "guidingFrameNoise": 0.02,
    "height": 512,
    "hiresFix": false,
    "hiresFixHeight": 448,
    "hiresFixStrength": 0.7,
    "hiresFixWidth": 448,
    "id": 0,
    "imageGuidanceScale": 1.5,
    "imagePriorSteps": 5,
    "loras": [],
    "maskBlur": 1.5,
    "maskBlurOutset": 0,
    "model": "sd_v1.5_f16.ckpt",
    "motionScale": 127,
    "negativeAestheticScore": 2.5,
    "negativeOriginalImageHeight": 0,
    "negativeOriginalImageWidth": 0,
    "negativePromptForImagePrior": true,
    "numFrames": 14,
    "originalImageHeight": 0,
    "originalImageWidth": 0,
    "preserveOriginalAfterInpaint": true,
    "refinerStart": 0.85,
    "sampler": 0,
    "seed": 1316122616,
    "seedMode": 2,
    "sharpness": 0,
    "shift": 1,
    "stage2Guidance": 1,
    "stage2Shift": 1,
    "stage2Steps": 10,
    "startFrameGuidance": 1,
    "steps": 30,
    "stochasticSamplingGamma": 0.3,
    "strength": 1,
    "targetImageHeight": 0,
    "targetImageWidth": 0,
    "tiledDecoding": false,
    "tiledDiffusion": false,
    "upscalerScaleFactor": 0,
    "width": 512,
    "zeroNegativePrompt": false
}
